### PR TITLE
Use support stream config as much as possible

### LINKED ISSUE #36: Cannot build output stream.: StreamConfigNotSupported
I'm getting an error when trying to stream audio.  I talked to you earlier on Discord.  Thanks for your help.

```
thread 'Async Compute Task Pool (1)' panicked at 'Cannot build output stream.: StreamConfigNotSupported', C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_oddio-0.2.0\src\output.rs:90:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Async Compute Task Pool (0)' panicked at 'Cannot build output stream.: StreamConfigNotSupported', C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_oddio-0.2.0\src\output.rs:90:10
```

```rust
use bevy::{
    prelude::{*, App, Assets, Commands, Handle, Res, ResMut, StartupStage},
    reflect::TypeUuid,
};
use bevy_renet::renet::RenetClient;
use bevy_steamworks::Client;
use iyes_loopless::prelude::*;
use bevy_oddio::{
    frames::Mono, oddio, output::AudioSink, Audio, AudioApp,
    ToSignal,
};

const VOICE_OUTPUT_SAMPLE_RATE: u32 = 11025;
const BYTES_PER_SAMPLE: u32 = 2;


pub struct VoicePlugin;

impl Plugin for VoicePlugin {
    fn build(&self, app: &mut App) {
        app
            .insert_resource(VoiceInput::default())
            .add_audio_source::<1, _, NetworkAudio>()
            .add_startup_system(init_assets)
            .add_startup_system_to_stage(StartupStage::PostStartup, init_audio)
            .add_system(receive_voice_messages.run_in_state(GameState::InGame).run_in_state(PlayerState::Spawned))
        ;
    }
}




// We create a marker struct to act as a dummy asset.
//
// This mirrors how bevy_audio works internally 
// by handling `Handle<AudioSource>` instead of AudioSource itself.
// The reason is for audio loader ergonomics.
// The consequence is that generative and programmatic usage of audio is harder. 
#[derive(TypeUuid)]
#[uuid = "ac7dad95-8e57-4180-a04e-71da19cbdc88"]
struct NetworkAudio;

// All audio assets in bevy_oddio requires `ToSignal`.
// This is the conversion from asset form to the actual `oddio::Signal`
impl ToSignal for NetworkAudio {
    // Settings needed for initializing `oddio::Stream`. See the documentation there.
    type Settings = (u32, usize);
    // The actual signal. It uses Mono instead of f32 because Asset must be implemented.
    type Signal = oddio::Stream<Mono>;

    fn to_signal(&self, settings: Self::Settings) -> Self::Signal {
        oddio::Stream::new(settings.0, settings.1)
    }
}

// This is the Handle of the NetworkAudio.
// We need this to play the audio.
struct NetworkAudioHandle(Handle<NetworkAudio>);
// This is the handle to the audio sink.
// We need this to control the audio.
struct NetworkAudioSink(Handle<AudioSink<NetworkAudio>>);

// We simply initialize the asset as a startup system.
fn init_assets(mut commands: Commands, mut assets: ResMut<Assets<NetworkAudio>>) {
    let handle = assets.add(NetworkAudio);
    commands.insert_resource(NetworkAudioHandle(handle));
}

// We add the oddio::Stream to the audio mixer.
fn init_audio(
    mut commands: Commands,
    mut audio: ResMut<Audio<Mono, NetworkAudio>>,
    network_audio: Res<NetworkAudioHandle>,
) {
    let handle = audio.play(network_audio.0.clone(), (VOICE_OUTPUT_SAMPLE_RATE , 64));
    commands.insert_resource(NetworkAudioSink(handle));
}


fn receive_voice_messages (
    resnet: Option<ResMut<RenetClient>>,
    steam_client: Res<Client>,
    sink_handle: Res<NetworkAudioSink>,
    mut sinks: ResMut<Assets<AudioSink<NetworkAudio>>>,
) {
    match resnet {
        Some(mut client) => {
            while let Some(message) = client.receive_message(ToClientChannel::ReceiveVoiceChannel.id()) {

                let mut p_dest_buffer: Vec<u8> = vec![0; (VOICE_OUTPUT_SAMPLE_RATE * BYTES_PER_SAMPLE).try_into().unwrap()];
                let cb_dest_buffer_size: u32 = VOICE_OUTPUT_SAMPLE_RATE * BYTES_PER_SAMPLE;
                let mut n_bytes_written: u32 = 0;

                let res = steam_client.user().decompress_voice(
                    &message,
                    &mut p_dest_buffer,
                    cb_dest_buffer_size,
                    &mut n_bytes_written,
                    VOICE_OUTPUT_SAMPLE_RATE,
                );

                match res {
                    Ok(_) => {
                        if n_bytes_written > 0 {
                            let sink = match sinks.get_mut(&sink_handle.0) {
                                Some(sink) => sink,
                                None => return,
                            };

                            let audio_bytes: Vec<Mono> = p_dest_buffer
                                .into_iter()
                                // We need to convert u8 to f32. [-1, 1]
                                .map(|x| (x as f32) / (u8::MAX as f32))
                                .map(|x| (x * 2.0) - 1.0)
                                // We need to convert the frame to its asset form.
                                .map(|x| Mono::from([x,]))
                                .collect();

                            sink.control::<oddio::Stream<_>, _>().write(&audio_bytes);
                        }
                    },
                    Err(err) => {
                        info!("error receiving voice: {:?}", err);
                    },
                }
            }
        }
        
        None => ()
    }
}
```

### PR DESCRIPTION
**Pull request by harudagondi**
# Objective

- Closes #36.

## Solution

- Use the supported stream config as much as possible.
- Change buffer size to supported buffer size.

### CODE REVIEW

**Comment by harudagondi** [comment]
@dan335 can you check if this PR works on your end?

**Comment by dan335** [comment]
Unfortunately I still get the error.  

```
PS D:\rust\bevy_oddio> cargo run --example noise
   Compiling bevy_oddio v0.2.0 (D:\rust\bevy_oddio)
    Finished dev [unoptimized + debuginfo] target(s) in 9.99s
     Running `target\debug\examples\noise.exe`
2022-09-22T14:12:04.007551Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 3070 Ti", vendor: 4318, device: 9346, device_type: DiscreteGpu, backend: Vulkan }
thread 'Async Compute Task Pool (0)' panicked at 'Cannot build output stream.: StreamConfigNotSupported', src\output.rs:99:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Async Compute Task Pool (3)' panicked at 'Cannot build output stream.: StreamConfigNotSupported', src\output.rs:99:10
```

If I can do anything to help like maybe chat on Discord and try some things let me know.

**Comment by harudagondi** [comment]
Can you test the `sine` example?

**Comment by dan335** [comment]
Same error.

```
PS D:\rust\bevy_oddio> cargo run --example sine
   Compiling bevy_oddio v0.2.0 (D:\rust\bevy_oddio)
    Finished dev [unoptimized + debuginfo] target(s) in 9.12s
     Running `target\debug\examples\sine.exe`
2022-09-22T14:31:01.561715Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 3070 Ti", vendor: 4318, device: 9346, device_type: DiscreteGpu, backend: Vulkan }
thread 'Async Compute Task Pool (2)' panicked at 'Cannot build output stream.: StreamConfigNotSupported', src\output.rs:99:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Async Compute Task Pool (1)' panicked at 'Cannot build output stream.: StreamConfigNotSupported', src\output.rs:99:10
```

**Comment by harudagondi** [comment]
Hey can you test this again?

**Comment by dan335** [comment]
Still getting it.

```
PS D:\rust\bevy_oddio> git pull
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), 495 bytes | 123.00 KiB/s, done.
From github.com:harudagondi/bevy_oddio
   f62d662..4ea1beb  fix-stream-config -> origin/fix-stream-config
Updating f62d662..4ea1beb
Fast-forward
 src/output.rs | 23 ++++++++++++++---------
 1 file changed, 14 insertions(+), 9 deletions(-)
PS D:\rust\bevy_oddio> cargo run --example sine
   Compiling bevy_oddio v0.2.0 (D:\rust\bevy_oddio)
    Finished dev [unoptimized + debuginfo] target(s) in 9.97s
     Running `target\debug\examples\sine.exe`
2022-09-22T14:38:48.484895Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 3070 Ti", vendor: 4318, device: 9346, device_type: DiscreteGpu, backend: Vulkan }
thread 'Async Compute Task Pool (3)' panicked at 'Cannot build output stream.: StreamConfigNotSupported', src\output.rs:104:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Async Compute Task Pool (1)' panicked at 'Cannot build output stream.: StreamConfigNotSupported', src\output.rs:104:10
```

**Comment by harudagondi** [comment]
Okay i literally copy pasted the code that worked on your machine lol. Can you show the backtrace?

**Comment by dan335** [comment]
```
PS D:\rust\bevy_oddio> cargo run --example sine
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target\debug\examples\sine.exe`
2022-09-22T14:46:53.839753Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 3070 Ti", vendor: 4318, device: 9346, device_type: DiscreteGpu, backend: Vulkan }
thread 'Async Compute Task Pool (2)' panicked at 'Cannot build output stream.: StreamConfigNotSupported', src\output.rs:104:10
stack backtrace:
thread 'Async Compute Task Pool (1)' panicked at 'Cannot build output stream.: StreamConfigNotSupported', src\output.rs:104:10
   0: rust_begin_unwind
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library\std\src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library\core\src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library\core\src/result.rs:1785:5
   3: core::result::Result<T,E>::expect
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90\library\core\src/result.rs:1064:23
   4: bevy_oddio::output::play
             at .\src\output.rs:87:18
   5: <bevy_oddio::output::AudioOutput<_,F> as core::default::Default>::default::{{closure}}
             at .\src\output.rs:57:33
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90\library\core\src\future/mod.rs:91:19
   7: async_executor::Executor::spawn::{{closure}}
             at C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.1\src\lib.rs:144:19
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90\library\core\src\future/mod.rs:91:19
   9: async_task::raw::RawTask<F,T,S>::run
             at C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.3.0\src\raw.rs:511:20
  10: async_task::runnable::Runnable::run
             at C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.3.0\src\runnable.rs:309:18
  11: async_executor::Executor::run::{{closure}}::{{closure}}
             at C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.1\src\lib.rs:235:21
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90\library\core\src\future/mod.rs:91:19
  13: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:529:33
  14: async_executor::Executor::run::{{closure}}
             at C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.1\src\lib.rs:242:31
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90\library\core\src\future/mod.rs:91:19
  16: futures_lite::future::block_on::{{closure}}
             at C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:89:27
  17: std::thread::local::LocalKey<T>::try_with
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90\library\std\src\thread/local.rs:445:16
  18: std::thread::local::LocalKey<T>::with
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90\library\std\src\thread/local.rs:421:9
  19: futures_lite::future::block_on
             at C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:79:5
  20: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}
             at C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.8.1\src\task_pool.rs:120:25
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library\std\src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library\core\src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library\core\src/result.rs:1785:5
   3: core::result::Result<T,E>::expect
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90\library\core\src/result.rs:1064:23
   4: bevy_oddio::output::play
             at .\src\output.rs:87:18
   5: <bevy_oddio::output::AudioOutput<_,F> as core::default::Default>::default::{{closure}}
             at .\src\output.rs:57:33
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90\library\core\src\future/mod.rs:91:19
   7: async_executor::Executor::spawn::{{closure}}
             at C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.1\src\lib.rs:144:19
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90\library\core\src\future/mod.rs:91:19
   9: async_task::raw::RawTask<F,T,S>::run
             at C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.3.0\src\raw.rs:511:20
  10: async_task::runnable::Runnable::run
             at C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.3.0\src\runnable.rs:309:18
  11: async_executor::Executor::run::{{closure}}::{{closure}}
             at C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.1\src\lib.rs:235:21
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90\library\core\src\future/mod.rs:91:19
  13: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:529:33
  14: async_executor::Executor::run::{{closure}}
             at C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.1\src\lib.rs:242:31
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90\library\core\src\future/mod.rs:91:19
  16: futures_lite::future::block_on::{{closure}}
             at C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:89:27
  17: std::thread::local::LocalKey<T>::try_with
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90\library\std\src\thread/local.rs:445:16
  18: std::thread::local::LocalKey<T>::with
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90\library\std\src\thread/local.rs:421:9
  19: futures_lite::future::block_on
             at C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:79:5
  20: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}
             at C:\Users\danph\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.8.1\src\task_pool.rs:120:25
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by dan335** [comment]
doing this gets rid of the error.

```rust
let host = cpal::default_host();
    let device = host
        .default_output_device()
        .expect("no output device available");
    let sample_rate = device.default_output_config().unwrap().sample_rate();
    let con = cpal::StreamConfig {
        channels: 2,
        sample_rate,
        buffer_size: cpal::BufferSize::Default,
    };

    let stream = device
        .build_output_stream(
            &con,
            move |out_flat: &mut [f32], _: &cpal::OutputCallbackInfo| {
                assert_eq!(
                    out_flat.len() % N,
                    0,
                    "`N` must be a power of 2 that is less than or equal to the output buffer in cpal."
                );
                // Safety:
                // (1) `F` implements `FromFrame<[Sample; N]>`.
                // (2) out_flat.len() is divisible by `N`.
                let out_n = unsafe { frame_n(out_flat) };
                oddio::run(&mixer, config.sample_rate.0, out_n);
            },
            move |err| bevy::utils::tracing::error!("Error in cpal: {err:?}"),
        )
        .expect("Cannot build output stream.");
    stream.play().expect("Cannot play stream.");
```

**Comment by dan335** [comment]
That latest commits runs with no error.  :D

**Comment by dan335** [comment]
I tried changing the sample rate to see if that also caused it and the error came back.

```rust
let config = cpal::StreamConfig {
        channels: supported_config_range.channels(),
        sample_rate: cpal::SampleRate(41000),
        buffer_size,
    };
```

**Comment by dan335** [comment]
Great!  :D

**Comment by harudagondi** [comment]
> I tried changing the sample rate to see if that also caused it and the error came back.
> 
> ```rust
> let config = cpal::StreamConfig {
>         channels: supported_config_range.channels(),
>         sample_rate: cpal::SampleRate(41000),
>         buffer_size,
>     };
> ```

Yeah, to know your supported configs, you should run this:

```rust
use cpal::traits::{DeviceTrait, HostTrait};

fn main() {
    let host = cpal::default_host();

    let device = host
        .default_output_device()
        .expect("There is no output device?");

    let supported_output_configs = device.supported_output_configs();

    for config in supported_output_configs.unwrap() {
        println!("{config:?}");
    }
}
```

**Pull request merged**
